services:
  - type: web
    name: pinkbasket-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: ohio
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8001

  - type: static
    name: pinkbasket-frontend
    region: ohio
    branch: main
    buildCommand: npm install && npm run build
    publishPath: ./dist
