name: PinkBasket CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Frontend Dependencies
      run: npm ci

    - name: Run Frontend Linter
      run: npm run lint

    - name: Build Frontend
      run: npm run build

    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm ci

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Test Docker Compose Build
      run: docker-compose build
